# - !<GS200>
#   id: 91x336839
#   name: yoko1
# - !<LMS>
#   id: 25334
#   name: lo_qubit
# - !<LMS>
#   id: 25330
#   name: lo_rr
- !<SA124>
 id: 19184645
 name: sa_snail
- !<SA124>
 id: 20234154
 name: sa_readout
- !<APUASYN20>
 id: 915-0M1040000-0081
 name: anapico #apuasyn20
# - !<LMS>
#   id: 25331
#   name: lo_cav
- !<OPXPlus>
  name: opx_plus
  id: 192.168.111.147
  cluster_name: Cluster_2