# - !<LMS>
#   id: 25332
#   name: lo_qubit
# - !<LMS>
#   id: 25331
#   name: lo_rr
# #- !<SA124>
# #  id: 20234564
# #  name: sa
# - !<LMS>
#   id: 25330
#   name: lo_cav
# - !<GS200>
#   id: 91X336839
#   name: yoko1
# - !<GS200>
#   id: 9
#   name: yoko2
- !<OPX1000>
  name: opx1000
  id: 192.168.111.181
  cluster_name: Cluster_1
