- !<Qubit>
  name: qubit
  int_freq: 1.700000E+08
  lo_name: opx1000
  mixer_offsets:
    I: 0.0
    Q: 0.0
    G: 0.0
    P: 0.0
  octave_mixed: true
  operations:
    qubit_constant_pulse: !<ConstantPulse>
      name: qubit_constant_pulse
      I_ampx: 0.6
      Q_ampx: 0.0
      digital_marker: null
      length: 100
      pad: 0
      total_I_amp: 0.12
      total_length: 100
    qubit_pi_10: !<GaussianPulse>
      name: qubit_pi_10
      I_ampx: 2.4
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 11
      total_I_ampx: 0.48
      total_length: 44
    qubit_pi2_10: !<GaussianPulse>
      name: qubit_pi2_10
      I_ampx: 1.2
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 11
      total_I_ampx: 0.24
      total_length: 44
    qubit_pi_100: !<GaussianPulse>
      name: qubit_pi_100
      I_ampx: 0.132013201320132
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 100
      total_I_ampx: 0.026402640264026403
      total_length: 400
    qubit_pi_200: !<GaussianPulse>
      name: qubit_pi_200
      I_ampx: 0.066006600660066
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 200
      total_I_ampx: 0.013201320132013201
      total_length: 800
    qubit_pi_400: !<GaussianPulse>
      name: qubit_pi_400
      I_ampx: 0.033003300330033
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 400
      total_I_ampx: 0.006600660066006601
      total_length: 1600
  ports:
    I:
    - 2
    - 6
  rf_switch: null
  rf_switch_on: false
- !<Qubit>
  name: snail
  int_freq: 49806500
  lo_name: opx1000
  mixer_offsets:
    I: 0.0
    Q: 0.0
    G: 0.0
    P: 0.0
  octave_mixed: true
  operations:
    qubit_detuned_pi_9: !<GaussianPulse>
      name: qubit_detuned_pi_9
      I_ampx: 2.3401
      Q_ampx: -0.01425
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 9
      total_I_ampx: 0.46802000000000005
      total_length: 36
    qubit_detuned_pi2_su8: !<SuperGaussianPulse>
      name: qubit_detuned_pi2_su8
      I_ampx: 1.49925
      Q_ampx: -0.0175
      chop: 3
      digital_marker: null
      pad: 0
      sigma: 8
      total_I_ampx: 0.29985
      total_length: 24
  ports:
    I:
    - 2
    - 6
  rf_switch: null
  rf_switch_on: false
- !<Cavity>
  name: cavity
  int_freq: -6.830000E+07
  lo_name: opx1000
  mixer_offsets:
    I: -0.003281430326023839
    Q: 0.007301341287165995
    G: 0.1829767245231779
    P: -0.15609249742628886
  octave_mixed: true
  operations:
    alice_constant: !<ConstantPulse>
      name: alice_constant
      I_ampx: 2.4
      Q_ampx: 0.0
      digital_marker: null
      length: 400
      pad: 0
      total_I_amp: 0.48
      total_length: 400
    a_d_large: !<GaussianPulse>
      name: a_d_large
      I_ampx: 1.5
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 800
      total_I_ampx: 0.30000000000000004
      total_length: 3200
  ports:
    I:
    - 2
    - 2
  rf_switch: null
  rf_switch_on: false
- !<Cavity>
  name: cavity_m
  int_freq: -6.830000E+07
  lo_name: opx1000
  mixer_offsets:
    I: -0.003281430326023839
    Q: 0.007301341287165995
    G: 0.1829767245231779
    P: -0.15609249742628886
  octave_mixed: true
  operations:
    alice_constant: !<ConstantPulse>
      name: alice_constant
      I_ampx: 2.4
      Q_ampx: 0.0
      digital_marker: null
      length: 400
      pad: 0
      total_I_amp: 0.48
      total_length: 400
    a_d_large: !<GaussianPulse>
      name: a_d_large
      I_ampx: 1.5
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 800
      total_I_ampx: 0.30000000000000004
      total_length: 3200
  ports:
    I:
    - 2
    - 2
  rf_switch: null
  rf_switch_on: false
- !<Readout>
  name: rr
  int_freq: 1.036000E+08
  lo_name: opx1000
  mixer_offsets:
    I: 0.0
    Q: 0.0
    G: 0.0
    P: 0.0
    out1: 0
    out2: 0
    out: 0.0
  octave_mixed: false
  operations:
    rr_readout_pulse: !<ConstantReadoutPulse>
      name: rr_readout_pulse
      I_ampx: 0.20181223654314717
      Q_ampx: 0.0
      digital_marker: !<DigitalWaveform>
        name: ADC_ON
        samples: &id002
        - - 1
          - 0
      has_optimized_weights: false
      length: 3520
      pad: 256
      threshold: -1.924936700552233e-06
      total_I_amp: 0.04036244730862944
      total_length: 3776
      weights: &id003
      - 1.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - -1.0
    rr_opt_CLEAR_readout_pulse_before0812_longer: !<ClearReadoutPulse>
      name: rr_opt_CLEAR_readout_pulse_before0812_longer
      I_ampx: 0.7128000000000001
      Q_ampx: 0.0
      digital_marker: !<DigitalWaveform>
        name: ADC_ON
        samples: *id002
      drive_amp: 0.30000000000000004
      drive_time: 2011
      has_optimized_weights: false
      length: 2469
      pad: 27
      ringdown1_amp: 0.04626817584679196
      ringdown1_time: 139
      ringdown2_amp: -0.3227494384599977
      ringdown2_time: 86
      ringup1_amp: 0.5995834173300624
      ringup1_time: 37
      ringup2_amp: 0.016291156023338596
      ringup2_time: 196
      threshold: 6.596045318794056e-06
      total_I_amp: 0.7128000000000001
      total_length: 2496
      weights: *id003
    rr_opt_CLEAR_readout_pulse_before0812_smaller_ampx: !<ClearReadoutPulse>
      name: rr_opt_CLEAR_readout_pulse_before0812_smaller_ampx
      I_ampx: 1.4400000000000002
      Q_ampx: 0.0
      digital_marker: !<DigitalWaveform>
        name: ADC_ON
        samples: *id002
      drive_amp: 0.30000000000000004
      drive_time: 731
      has_optimized_weights: true
      length: 1189
      pad: 27
      ringdown1_amp: 0.04626817584679196
      ringdown1_time: 139
      ringdown2_amp: -0.3227494384599977
      ringdown2_time: 86
      ringup1_amp: 0.5995834173300624
      ringup1_time: 37
      ringup2_amp: 0.016291156023338596
      ringup2_time: 196
      threshold: 8.460966209147704e-06
      total_I_amp: 1.4400000000000002
      total_length: 1216
      weights: C:\Users\qcrew\Documents\jon\cheddar\config\weights\20251111_105444_weights.npz
    rr_displacement: !<ConstantPulse>
      name: rr_displacement
      I_ampx: 0.0
      Q_ampx: 0.0
      digital_marker: null
      length: 100
      pad: 0
      total_I_amp: 0.0
      total_length: 100
    qubit_empty_9: !<GaussianPulse>
      name: qubit_empty_9
      I_ampx: 0
      Q_ampx: 0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 9
      total_I_ampx: 0.0
      total_length: 36
  ports:
    I:
    - 2
    - 8
    out1:
    - 2
    - 2
  rf_switch: null
  rf_switch_on: false
  smearing: 0
  tof: 300
