- !<Qubit>
  name: qubit
  int_freq: 5.242000E+07
  lo_name: lo_qubit
  mixer_offsets:
    I: -0.0023203855264000636
    Q: -0.0043234245618805345
    G: -0.011521768569946297
    P: -0.10882945060729977
  octave_mixed: false
  operations:
    qubit_constant_pulse_10000: !<ConstantPulse>
      name: qubit_constant_pulse_10000
      I_ampx: 1.95
      Q_ampx: 0.0
      digital_marker: null
      length: 10000
      pad: 0
      total_I_amp: 0.39
      total_length: 10000
    qubit_constant_pulse_100: !<ConstantPulse>
      name: qubit_constant_pulse_100
      I_ampx: 1.95
      Q_ampx: 0.0
      digital_marker: null
      length: 100
      pad: 0
      total_I_amp: 0.39
      total_length: 100
    qubit_constant_pi_pulse_32: !<ConstantPulse>
      name: qubit_constant_pi_pulse_32
      I_ampx: 1.95
      Q_ampx: 0.0
      digital_marker: null
      length: 32
      pad: 0
      total_I_amp: 0.39
      total_length: 32
    qubit_constant_pi2_pulse_32: !<ConstantPulse>
      name: qubit_constant_pi2_pulse_32
      I_ampx: 0.55
      Q_ampx: 0.0
      digital_marker: null
      length: 32
      pad: 0
      total_I_amp: 0.11000000000000001
      total_length: 32
    spectrum_analysis_constant_pulse: !<ConstantPulse>
      name: spectrum_analysis_constant_pulse
      I_ampx: 1.0
      Q_ampx: 0.0
      digital_marker: null
      length: 1000
      pad: 0
      total_I_amp: 0.2
      total_length: 1000
    qubit_constant_pi_pulse_320: !<ConstantPulse>
      name: qubit_constant_pi_pulse_320
      I_ampx: 0.27
      Q_ampx: 0.0
      digital_marker: null
      length: 320
      pad: 0
      total_I_amp: 0.054000000000000006
      total_length: 320
    qubit_constant_pi_pulse_640: !<ConstantPulse>
      name: qubit_constant_pi_pulse_640
      I_ampx: 0.5
      Q_ampx: 0.0
      digital_marker: null
      length: 640
      pad: 0
      total_I_amp: 0.1
      total_length: 640
    qubit_constant_pi_pulse_800: !<ConstantPulse>
      name: qubit_constant_pi_pulse_800
      I_ampx: 0.007318548387096775
      Q_ampx: 0.0
      digital_marker: null
      length: 800
      pad: 0
      total_I_amp: 0.001463709677419355
      total_length: 800
    qubit_gaussian_pi_4: !<GaussianPulse>
      name: qubit_gaussian_pi_4
      I_ampx: 0.2569935130725405
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 4
      total_I_ampx: 0.0513987026145081
      total_length: 16
    qubit_gaussian_pi2_4: !<GaussianPulse>
      name: qubit_gaussian_pi2_4
      I_ampx: 0.12849675653627024
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 4
      total_I_ampx: 0.02569935130725405
      total_length: 16
    qubit_gaussian_pi_pulse: !<GaussianPulse>
      name: qubit_gaussian_pi_pulse
      I_ampx: 0.7014
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 40
      total_I_ampx: 0.14028000000000002
      total_length: 160
    qubit_gaussian_pi_pulse_200: !<GaussianPulse>
      name: qubit_gaussian_pi_pulse_200
      I_ampx: 0.09784064278540341
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 200
      total_I_ampx: 0.019568128557080684
      total_length: 800
    qubit_cos_ramp_pulse: !<RampedConstantPulse>
      name: qubit_cos_ramp_pulse
      I_ampx: 1.4
      Q_ampx: 0.0
      digital_marker: null
      length: 20
      pad: 0
      ramp: 10
      rampfn: cos
      total_I_amp: 0.27999999999999997
      total_length: 40
  ports:
    I: 1
    Q: 2
  rf_switch: null
  rf_switch_on: false
- !<Qubit>
  name: qubitEF
  int_freq: -1.246000E+08
  lo_name: lo_qubit
  mixer_offsets:
    I: 0.0071526846615597595
    Q: 0.005089394142851233
    G: 0.18711491525173193
    P: -0.10331471562385564
  octave_mixed: false
  operations:
    qubitEF_constant_pulse_10000: !<ConstantPulse>
      name: qubitEF_constant_pulse_10000
      I_ampx: 0.5
      Q_ampx: 0.0
      digital_marker: null
      length: 10000
      pad: 0
      total_I_amp: 0.1
      total_length: 10000
    qubitEF_constant_pi_pulse: !<ConstantPulse>
      name: qubitEF_constant_pi_pulse
      I_ampx: 1
      Q_ampx: 0.0
      digital_marker: null
      length: 52
      pad: 0
      total_I_amp: 0.2
      total_length: 52
    qubitEF_constant_pi_pulse_400: !<ConstantPulse>
      name: qubitEF_constant_pi_pulse_400
      I_ampx: 1.33
      Q_ampx: 0.0
      digital_marker: null
      length: 400
      pad: 0
      total_I_amp: 0.266
      total_length: 400
    qubitEF_constant_pi_pulse_96: !<ConstantPulse>
      name: qubitEF_constant_pi_pulse_96
      I_ampx: 1
      Q_ampx: 0.0
      digital_marker: null
      length: 96
      pad: 0
      total_I_amp: 0.2
      total_length: 96
    qubitEF_constant_pi_pulse_28: !<ConstantPulse>
      name: qubitEF_constant_pi_pulse_28
      I_ampx: 0.3
      Q_ampx: 0.0
      digital_marker: null
      length: 28
      pad: 0
      total_I_amp: 0.06
      total_length: 28
    qubitEF_constant_pi_pulse_300: !<ConstantPulse>
      name: qubitEF_constant_pi_pulse_300
      I_ampx: 1.33
      Q_ampx: 0.0
      digital_marker: null
      length: 300
      pad: 0
      total_I_amp: 0.266
      total_length: 300
    qubitEF_constant_pi2_pulse: !<ConstantPulse>
      name: qubitEF_constant_pi2_pulse
      I_ampx: 0.2975
      Q_ampx: 0.0
      digital_marker: null
      length: 52
      pad: 0
      total_I_amp: 0.0595
      total_length: 52
    qubitEF_constant_selective_pi_pulse: !<ConstantPulse>
      name: qubitEF_constant_selective_pi_pulse
      I_ampx: 0.032
      Q_ampx: 0.0
      digital_marker: null
      length: 1000
      pad: 0
      total_I_amp: 0.0064
      total_length: 1000
    qubitEF_constant_very_selective_pi_pulse: !<ConstantPulse>
      name: qubitEF_constant_very_selective_pi_pulse
      I_ampx: 0.008
      Q_ampx: 0.0
      digital_marker: null
      length: 4000
      pad: 0
      total_I_amp: 0.0016
      total_length: 4000
    qubitEF_gaussian_pulse: !<GaussianPulse>
      name: qubitEF_gaussian_pulse
      I_ampx: 0.032
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 200
      total_I_ampx: 0.0064
      total_length: 800
    qubitEF_cos_ramp_pulse: !<RampedConstantPulse>
      name: qubitEF_cos_ramp_pulse
      I_ampx: 1.4
      Q_ampx: 0.0
      digital_marker: null
      length: 20
      pad: 0
      ramp: 10
      rampfn: cos
      total_I_amp: 0.27999999999999997
      total_length: 40
  ports:
    I: 1
    Q: 2
  rf_switch: null
  rf_switch_on: false
- !<Readout>
  name: rr
  int_freq: -5.000000E+07
  lo_name: lo_rr
  mixer_offsets:
    I: -0.01250000000000005
    Q: -0.02343749999999998
    G: -0.007812500000000017
    P: -0.003124999999999954
    out: -0.020806603064903846
  octave_mixed: false
  operations:
    rr_readout_pulse: !<ConstantReadoutPulse>
      name: rr_readout_pulse
      I_ampx: 1
      Q_ampx: 0.0
      digital_marker: !<DigitalWaveform>
        name: ADC_ON
        samples:
        - - 1
          - 0
      has_optimized_weights: false
      length: 400
      pad: 300
      threshold: null
      total_I_amp: 0.2
      total_length: 700
      weights:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - -1.0
    spectrum_analysis_constant_pulse: !<ConstantPulse>
      name: spectrum_analysis_constant_pulse
      I_ampx: 1.0
      Q_ampx: 0.0
      digital_marker: null
      length: 5000
      pad: 0
      total_I_amp: 0.2
      total_length: 5000
  ports:
    I: 5
    Q: 6
    out: 1
  rf_switch: null
  rf_switch_on: false
  smearing: 0
  tof: 272
- !<Cavity>
  name: cav
  int_freq: -1.100000E+08
  lo_name: lo_cav
  mixer_offsets:
    I: -0.01581861060694792
    Q: -0.0017682625242742
    G: -0.001791852293536067
    P: -0.12471660068258644
  octave_mixed: false
  operations:
    cav_constant_pulse_100000: !<ConstantPulse>
      name: cav_constant_pulse_100000
      I_ampx: 1.95
      Q_ampx: 0.0
      digital_marker: null
      length: 100000
      pad: 0
      total_I_amp: 0.39
      total_length: 100000
    cav_const_1: !<ConstantPulse>
      name: cav_const_1
      I_ampx: 1.95
      Q_ampx: 0.0
      digital_marker: null
      length: 160
      pad: 0
      total_I_amp: 0.39
      total_length: 160
    cav_cohstate_long: !<ConstantPulse>
      name: cav_cohstate_long
      I_ampx: 1.9
      Q_ampx: 0.0
      digital_marker: null
      length: 160
      pad: 0
      total_I_amp: 0.38
      total_length: 160
    cav_cohstate_superlong: !<ConstantPulse>
      name: cav_cohstate_superlong
      I_ampx: 1.9
      Q_ampx: 0.0
      digital_marker: null
      length: 10000
      pad: 0
      total_I_amp: 0.38
      total_length: 10000
    cav_gaussian_shortest: !<GaussianPulse>
      name: cav_gaussian_shortest
      I_ampx: 1.9
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 8
      total_I_ampx: 0.38
      total_length: 32
    cav_gaussian_long: !<GaussianPulse>
      name: cav_gaussian_long
      I_ampx: 0.5
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 40
      total_I_ampx: 0.1
      total_length: 160
    ECD_gaussian_1: !<GaussianPulse>
      name: ECD_gaussian_1
      I_ampx: 0.2
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 40
      total_I_ampx: 0.04000000000000001
      total_length: 160
    cav_gaussian_short: !<GaussianPulse>
      name: cav_gaussian_short
      I_ampx: 0.3
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 40
      total_I_ampx: 0.06
      total_length: 160
    spectrum_analysis_constant_pulse: !<ConstantPulse>
      name: spectrum_analysis_constant_pulse
      I_ampx: 1.0
      Q_ampx: 0.0
      digital_marker: null
      length: 1000
      pad: 0
      total_I_amp: 0.2
      total_length: 1000
  ports:
    I: 7
    Q: 8
  rf_switch: null
  rf_switch_on: false
